// Generated by unRap v1.06 by Kegetys
class CfgPatches {
	class wog_ru_kamaz{
		version = 0.1;
		units[] = {};
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {"A3_Armor_F", "A3_Soft_F", "A3_Air_F", "A3_Soft_F_Quadbike"};
	};
};
